apiVersion: apps/v1
kind: Deployment
metadata:
  name: cal-app
  namespace: webapps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calendar
  template:
    metadata:
      name: cal-apps
      labels:
        app: calendar
    spec:
      containers:
        - name: calendar-app
          image: ari786/calendar:v4.0
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cal-svc
  namespace: webapps
spec:
  type: NodePort
  selector:
    app: calendar
  ports:
    - port: 80
      targetPort: 80
      protocol: 'TCP'
    